## 3. Lists in Python

* A `List` in Python is a mutable(Can be changes), Ordered, Indexed collections that can store multiple values.
* Including(Mixed data type)
* Lists are one of most used data types in python.


### 1. List Definition

---
Syntax:
`my_list = [1,2,3]`

In [2]:
myList = []
print(myList,type(myList))

[] <class 'list'>

In [3]:
data = [10,20,30]
print(data)

[10, 20, 30]

## 2. Feature of List

---
|Feature|Explanation|
|---|---|
|Ordered|Item maintain insertion order|
|Indexed|Each element has an index|
|Mutable|Can be modify after creation|
|Allows Duplicate|Same values can repeat|
|Mixed types allowed| int, float, str, bool, object-[string, list, tuple, set, dictionary]

In [5]:
x = [10,25.85,"python",True,False, [10,20],(10,14),{10,12},{"a":"apple"}]
print(x)

[10, 25.85, 'python', True, False, [10, 20], (10, 14), {10, 12}, {'a': 'apple'}]

### Index - Positive

In [8]:
print(x[0])
print(x[1])
print(x[2])
print(x[3])
print(x[4])
print(x[5])
print(x[6])
print(x[7])
print(x[8])

10
25.85
python
True
False
[10, 20]
(10, 14)
{10, 12}
{'a': 'apple'}

### Index Negative

In [10]:
print(x[-1])
print(x[-2])
print(x[-3])
print(x[-4])
print(x[-5])
print(x[-6])
print(x[-7])
print(x[-8])
print(x[-9])

{'a': 'apple'}
{10, 12}
(10, 14)
[10, 20]
False
True
python
25.85
10

## type()

In [14]:
print(x[0])
print(type(x[0]))

print(x[1])
print(type(x[1]))

print(x[2])
print(type(x[2]))

10
<class 'int'>
25.85
<class 'float'>
python
<class 'str'>

In [15]:
x = [10,25.85,"python",True,False, [10,20],(10,14),{10,12},{"a":"apple"}]
print(x)

[10, 25.85, 'python', True, False, [10, 20], (10, 14), {10, 12}, {'a': 'apple'}]

## 4. Slicing of List

`var[start:end]`

In [16]:
x[0:5]

[10, 25.85, 'python', True, False]

In [17]:
x[7:9]

[{10, 12}, {'a': 'apple'}]

In [19]:
x[3:7]

[True, False, [10, 20], (10, 14)]

In [22]:
x = [10,[10,20,30],[[10,20,50],True,False],[14,17,89],("Python",50),30,60,78,90]

x[2][0][0]

10

In [25]:
x[4][0]  # accessing elements

'Python'

In [27]:
x[4][0:1] # slicing

('Python',)

In [29]:
x[2][1:3]

[True, False]

In [31]:
x[2][1:3]

IndexError: list index out of range

In [32]:
x[6:9]

[]

In [35]:
x = [10,[10,20,30],[[10,20,50],True,False],[14,17,89],("Python",50),30,60,78,90]
print(x)

[10, [10, 20, 30], [[10, 20, 50], True, False], [14, 17, 89], ('Python', 50), 30, 60, 78, 90]

In [36]:
x[6:9]

[60, 78, 90]

In [40]:
x[2][0][1:3]

[20, 50]

In [41]:
x1 = ["Python",[[100,50,[10,20,"Tanaz"],"Hello world",80,45],[["Python",[55,44,[55.36,"Arbaz"]],]],[["Pune","Delhi","Hemant"]]]]
print(x1)

['Python', [[100, 50, [10, 20, 'Tanaz'], 'Hello world', 80, 45], [['Python', [55, 44, [55.36, 'Arbaz']]]], [['Pune', 'Delhi', 'Hemant']]]]

In [46]:
x1[1][0][2][2:3]

['Tanaz']

In [50]:
x1[1][2][0][2:3]

['Hemant']

In [56]:
x1[1][1][0][1][2][1:2]

['Arbaz']

### 5. Striging of Lists

`var[start:end:skip]`

In [1]:
x1 = ["Python",[[100,50,[10,20,"Tanaz"],"Hello world",80,45],[["Python",[55,44,[55.36,"Arbaz"]],]],[["Pune","Delhi","Hemant"]]]]
print(x1)

['Python', [[100, 50, [10, 20, 'Tanaz'], 'Hello world', 80, 45], [['Python', [55, 44, [55.36, 'Arbaz']]]], [['Pune', 'Delhi', 'Hemant']]]]

In [2]:
x1[::2]

['Python']

In [3]:
x1[::]

['Python',
 [[100, 50, [10, 20, 'Tanaz'], 'Hello world', 80, 45],
  [['Python', [55, 44, [55.36, 'Arbaz']]]],
  [['Pune', 'Delhi', 'Hemant']]]]

### 6. List is mutable(changeable)

In [4]:
data= [10,20,30,50,60,70]
print(data)

[10, 20, 30, 50, 60, 70]

In [5]:
print(type(data))

<class 'list'>

In [7]:
data[0] = "Arbaz"
data

['Arbaz', 20, 30, 50, 60, 70]

In [9]:
data[2] = "Hemant"
data

['Arbaz', 20, 'Hemant', 50, 60, 70]

In [11]:
data[4] = "Tanaz"
data

['Arbaz', 20, 'Hemant', 50, 'Tanaz', 70]

In [13]:
str1 = "Hello world"  # string is immutable
str1[0] = 100
str1

TypeError: 'str' object does not support item assignment

### 6. Adding Elements to a list

1. append(): Adds element at the end one by one.

2. insert(): Adds element at any specific poisition.

3. extend(): Adds multiple elements at a time.

In [20]:
a = [1,2,3]
print(a)

[1, 2, 3]

In [21]:
a.append("Arbaz") # one parameter
print(a)

[1, 2, 3, 'Arbaz']

In [22]:
a.append("Arbaz",100) # one parameter
print(a)

TypeError: list.append() takes exactly one argument (2 given)

In [17]:
print(a)

[1, 2, 3, 'Arbaz']

### insert()

In [23]:
a

[1, 2, 3, 'Arbaz']

In [24]:
a.insert(0,"Tanaz")
a

['Tanaz', 1, 2, 3, 'Arbaz']

### extend()

In [25]:
a

['Tanaz', 1, 2, 3, 'Arbaz']

In [26]:
a.append([10,20])
a

['Tanaz', 1, 2, 3, 'Arbaz', [10, 20]]

In [27]:
a.extend([10,20])
a

['Tanaz', 1, 2, 3, 'Arbaz', [10, 20], 10, 20]

## 7. Removing Elements from the list

a). remove() : removes by value

b). pop(n) : n is index value, removes by index value.

c). pop(): Remove last element

d). clear(): remove all elemnets

e). del keyword

In [28]:
a= [10,20,30,50,60,70]

print(a)

[10, 20, 30, 50, 60, 70]

In [29]:
a.remove(20)  # 20 is value

In [30]:
a

[10, 30, 50, 60, 70]

In [31]:
a

[10, 30, 50, 60, 70]

In [32]:
a.pop(2)  # 2 is index value
a

[10, 30, 60, 70]

In [33]:
# pop() 

a.pop()

70

In [34]:
a

[10, 30, 60]

In [35]:
a.clear()
a

[]

In [36]:
a

[]

In [37]:
del(a)

In [38]:
a

NameError: name 'a' is not defined

In [39]:
a = ["apple",10,20]
a

['apple', 10, 20]

In [41]:
a[0] = "Banana"

In [43]:
a

['Banana', 10, 20]

In [45]:
"hello"
100

100

### 8. List Methods

---
|Method|Work|
|----|----|
|append(x)|add item at end|
|extend(iterable)|Add multiple items|
|insert(i,x)|i is index value and x is value|
|remove(n)| n is value|
|pop(n)| n is index value|
|pop()| remove last element|
|clear()| clear all values|
|del(n)|n is variable|
|index(x)| x is value return index value|
|count(x)| count occurrence of x value|
|reverse()| reverse the list|
|copy()| return shallow copy|

## 9.index(x) and count(x)

In [46]:
nums = [10,20,30,40,50,60,60,40,50,60,100]
print(nums)

[10, 20, 30, 40, 50, 60, 60, 40, 50, 60, 100]

In [47]:
nums.index(50)

4

In [48]:
nums.index(60) # first occurrence return

5

In [49]:
nums.count(10)

1

In [50]:
nums.count(50)

2

In [51]:
nums.count(60)

3

## 10. Sorting list

Data in Ascending or descending order

In [52]:
nums = [10,20,100,30,40,50,60,60,40,50,60]
print(nums)

[10, 20, 100, 30, 40, 50, 60, 60, 40, 50, 60]

In [53]:
nums.sort()  # arrange in ascending order
nums

[10, 20, 30, 40, 40, 50, 50, 60, 60, 60, 100]

## descending 

#### reverse()

In [54]:
nums.reverse()

In [55]:
nums

[100, 60, 60, 60, 50, 50, 40, 40, 30, 20, 10]

In [60]:
x = [10,9,7,55,22,33]
x.reverse()  # inbuild function
x

[33, 22, 55, 7, 9, 10]

In [57]:
nums = [10,20,100,30,40,50,60,60,40,50,60]
print(nums)

[10, 20, 100, 30, 40, 50, 60, 60, 40, 50, 60]

In [58]:
nums.sort()
nums

[10, 20, 30, 40, 40, 50, 50, 60, 60, 60, 100]

In [59]:
nums[::-1]  # slicing method

[100, 60, 60, 60, 50, 50, 40, 40, 30, 20, 10]

### Copy()

1. shallow copy(): reference copy
2. deep copy(): address copy()

1. shallow copy()

In [62]:
x = [10,20,30]
print("Original List:",x)


y = x.copy()
print("Copied Value:",y)

Original List: [10, 20, 30]
Copied Value: [10, 20, 30]

In [63]:
x.append(100)
x

[10, 20, 30, 100]

In [64]:
y

[10, 20, 30]

In [65]:
id(x)

2495688919872

In [66]:
id(y)

2495688901248

2. Deep Copy(): Address copy

In [68]:
x = [10,20,30]
print("Original List:",x)


y = x
print("Copied Value:",y)

Original List: [10, 20, 30]
Copied Value: [10, 20, 30]

In [69]:
id(x)

2495687929984

In [70]:
id(y)

2495687929984

In [71]:
x.append("apple")
x

[10, 20, 30, 'apple']

In [72]:
print(y)

[10, 20, 30, 'apple']

## 13. Nested List - [2-Dimension]

In [73]:
matrix = [
    [10,20,30],
    [40,50,60]
]
print(matrix)

[[10, 20, 30], [40, 50, 60]]

### Traversion List - 1-D

In [78]:
matrix = [
    [10,20,30],
    [40,50,60],
    [70,80,90]
]
print(matrix)

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [79]:
import pandas as pd

In [80]:
df= pd.DataFrame(matrix)
df

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

Traversion List - 1-D

Traverse

In [82]:
x = [10,20,30,40]  # 1-D
print(x)

[10, 20, 30, 40]

In [83]:
df1 = pd.DataFrame(x)
df1

    0
0  10
1  20
2  30
3  40

## 16. List Concaenation and Repetation

----

In [84]:
a = [10,20]
b = [15,30]
print(a)
print(b)

[10, 20]
[15, 30]

In [85]:
print(a+b) # concatenation

[10, 20, 15, 30]

In [86]:
a

[10, 20]

In [87]:
a*2  # repetation

[10, 20, 10, 20]

## 19. List VS Tuple

----
|List|Tuple|
|----|----|
|Mutable|Immutable|
|Uses:[]|Used:()|
|Slower|Faster|
|More memory| Less memory|
|Can be modifiy|cannot be modified|

### 20. List is mutable

In [88]:
a = [10,20,30,40,"Hello world",True,False]
a

[10, 20, 30, 40, 'Hello world', True, False]

In [90]:
a[4] = "Hello Arbaz"  # list updated
a

[10, 20, 30, 40, 'Hello Arbaz', True, False]